version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies...."
          npm install
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKERHUB_TOKEN" | docker login -u "DOCKERHUB_USERNAME" --password-stdin     
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t eggonion/build-and-push:latest .
            docker push eggonion/build-and-push:latest

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests...."
          npm run test
  optional_publish:
      # Assignment

  # publish_docker:
  #   docker:
  #     - image: cimg/node:16.10
  #   steps:
  #     - checkout
  #     - run:
  #         name: Log in to Docker Hub
  #         command: echo $GITHUB_TOKEN | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
  #     - run:
  #         name: Build Docker Image
  #         command: docker build -t docker.pkg.github.com/eggOnion/6m-software-4.5-ci-container/eggonion/build-and-push:latest .
  #     - run:
  #         name: Push Docker Image
  #         command: docker push docker.pkg.github.com/eggOnion/6m-software-4.5-ci-container/eggonion/build-and-push:latest

      # - node/install-packages:
      #     pkg-manager: npm
      # - docker/publish:
      #     name: build-and-push
      #     image: eggonion/build-and-push:latest
      #     username: $DOCKERHUB_USERNAME
      #     password: $DOCKERHUB_PASSWORD
      #
      

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build  