version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout      
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies...."
          npm install 
          
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - setup_remote_docker
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests...."
          npm run test
      - run:
          name: Log in to Docker Hub
          command: echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/build-and-push:latest_v1 .
            docker push $DOCKERHUB_USERNAME/build-and-push:latest_v1
  optional_publish:
      # Assignment

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build  